import mongoose from "mongoose";

const template = new mongoose.Schema({
  template: {
    type: String,
    required: true
  },
  templateName: {
    type: String,
    required: true
  },
  created_at: {
    type: Date,
    default: Date.now
  },
  updated_at: {
    type: Date,
    default: Date.now
  },
  visible: {
    type: Boolean,
    default: true
  },
  // Marketing copy generated by the template_validator agent (headline, description, useCases).
  // Mixed so the agent's schema can evolve without a migration here.
  meta: {
    type: mongoose.Schema.Types.Mixed,
    default: null
  }
});

const templateModel = mongoose.model("template", template);

export default templateModel;
